### ISSUE TITLE
XPLOAD_CONFIG env var seems to override config given in fetch arg list

### ISSUE THREAD

**Issue by pinkenburg** [BNLNPPS/xpload#20]
The XPLOAD_CONFIG env var was set to prod, 
the flag was set to sPHENIX_cdb, 
the XPLOAD_DIR env var set to /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/etc
The expectation is to read  /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/etc/sPHENIX_cdb.json returning
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/calibrations/DBTest/sphenix3dbigmapxyz.root

What is being read (apparently) is /cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/xpload-git/share/xpload/config/prod.json
prod.json has a typo which leads to a double slash in the fully qualified filename. The code to fetch the calibration creates a configurator using the flag:
      xpload::Configurator config(rc->get_StringFlag("XPLOAD_CONFIG"));
      xpload::Result result = xpload::fetch(rc->get_StringFlag("XPLOAD_TAG"), "FieldMap", 1234, config);

The result is
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/calibrations/DBTest//sphenix3dbigmapxyz.root
the // indicates that the configuration is ignored and what is being used is 
/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/xpload-git/share/xpload/config/prod.json

unsetting XPLOAD_CONFIG restores the expected behavior as does setting XPLOAD_CONFIG to sPHENIX_cdb

**Comment by plexoos** [comment]
Thanks for the report. The current logic is indeed to search for the configuration file in other directories until every location in the list is checked. I agree that this can be changed to look **only** in the directory set by an environment variable when such variable is defined. I will follow up on this in #19 shortly. I propose we also use a new name for such environment variable, i.e. `XPLOAD_CONFIG_DIR`, instead of `XPLOAD_DIR` because the former was supposed to have a different purpose of actually pointing to an <install_prefix> rather than a directory with configuration files.

**Comment by plexoos** [comment]
I guess I was still thinking about #19 while typing my response above. I hope this is a more relevant reply to this issue.

The statement in the title of this issue is correct. When XPLOAD_CONFIG is set it overrides whatever you pass to xpload::Configurator(). It is simply the result of these lines:

https://github.com/BNLNPPS/xpload/blob/4aa366b7178eb883451dbffea444d99628bfd24f/src/configurator.cpp#L16-L18

If you don't want XPLOAD_CONFIG to override the argument passed to xpload::Configurator() then why don't you just unset XPLOAD_CONFIG? One can view this environment variable as a way to switch to a different configuration without the need to recompile the code but setting it to anything is not required.

So, in your case you can either set rc->get_StringFlag("XPLOAD_CONFIG") to the same value as the environment variable XPLOAD_CONFIG or unset it.

**Comment by plexoos** [comment]
Resolved. See related #19
